[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

# X Layer Testnet (OKX) — Chain ID 195
[rpc_endpoints]
xlayer-testnet = "https://testrpc.xlayer.tech"
anvil = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md
